from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import utils
from io import BytesIO


def _load_image(path, width=None):
    try:
        img = utils.ImageReader(path)
        iw, ih = img.getSize()
        if width:
            ratio = width / float(iw)
            return img, width, ih * ratio
        return img, iw, ih
    except Exception:
        return None, 0, 0


def _draw_wrapped_text(c, text, x, y, max_width, leading=14):
    words = text.split()
    line = ""
    for word in words:
        test = f"{line} {word}".strip()
        if c.stringWidth(test, "Helvetica", 10) < max_width:
            line = test
        else:
            c.drawString(x, y, line)
            y -= leading
            line = word
    if line:
        c.drawString(x, y, line)
    return y - leading


def _draw_footer(c, page_width, text: str):
    """Draw a small footer centered at the bottom."""
    if not text:
        return
    c.setFont("Helvetica", 8)
    c.setFillColorRGB(0.4, 0.4, 0.4)  # soft grey
    c.drawCentredString(page_width / 2.0, 0.5 * inch, text)
    c.setFillColorRGB(0, 0, 0)  # reset to black


def create_consulting_brief_pdf(
    logo_path: str,
    domain: str,
    challenge: str,
    rule_based_summary: str,
    ai_brief: str,
    company_name: str = "Client",
    industry: str = "Finance",
    revenue=None,
    employees=None,
    footer_text: str = "Generated by Bivenue Copilot – AI-assisted Finance Transformation Advisor.",
):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # ---------------------------------------------------------
    #  HEADER: ONLY LOGO
    # ---------------------------------------------------------
    if logo_path:
        img, w, h = _load_image(logo_path, width=140)
        if img:
            c.drawImage(img, 40, height - 80, width=w, height=h, mask="auto")

    y = height - 120  # Move below logo

    # ---------------------------------------------------------
    #  TABLE HEADER: 3 COLUMNS
    # ---------------------------------------------------------
    col_width = (width - 80) / 3  # side margins
    x_positions = [40, 40 + col_width, 40 + (col_width * 2)]

    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_positions[0], y, "Mission-critical priority")
    c.drawString(x_positions[1], y, "How Bivenue helped")
    c.drawString(x_positions[2], y, "Outcome & AI deep-dive insights")

    y -= 25
    c.setFont("Helvetica", 10)

    # COLUMN 1 — Mission critical
    y1 = _draw_wrapped_text(
        c,
        f"Mission-critical priority: {domain}",
        x_positions[0],
        y,
        col_width - 10,
    )

    # COLUMN 2 — Rule-based recommendations (clean bullets)
    cleaned = (
        rule_based_summary.replace("■", "-")
        .replace("*", "")
        .replace("**", "")
        .strip()
    )

    y2 = _draw_wrapped_text(
        c,
        cleaned,
        x_positions[1],
        y,
        col_width - 10,
    )

    # COLUMN 3 — AI Insights preview
    ai_preview = ai_brief[:800] + "..." if len(ai_brief) > 800 else ai_brief

    y3 = _draw_wrapped_text(
        c,
        ai_preview,
        x_positions[2],
        y,
        col_width - 10,
    )

    # Continue below the lowest column
    y_after_table = min(y1, y2, y3) - 30

    # ---------------------------------------------------------
    #  FULL AI BRIEF SECTION
    # ---------------------------------------------------------
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y_after_table, "AI Full Consulting Brief")
    y_after_table -= 20

    c.setFont("Helvetica", 10)
    y_after_table = _draw_wrapped_text(
        c, ai_brief, 40, y_after_table, width - 80, leading=14
    )

    # FOOTER on this page
    _draw_footer(c, width, footer_text)

    c.showPage()
    c.save()

    buffer.seek(0)
    return buffer.getvalue()
